I also added description field for item to back end
elishaaquino/Senior-Project pull request #93
Opened 2020-12-15 23:09 UTC by mols2ma

2020-12-15 23:32 UTC, maggiechang reviewed
great job!

2020-12-15 23:37 UTC, elishaaquino requested changes

2020-12-15 23:37 UTC, elishaaquino commented on front-end/src/router.js
> +         path: "/store/:sellerId/:storename",
why is sellerid necessary?

2020-12-16 02:13 UTC, mols2ma commented on front-end/src/router.js
> +         path: "/store/:sellerId/:storename",
i haven't finished storepage. I just fixed add item in this pr

2020-12-16 07:42 UTC, merged